# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  build:
    cmds:
      - task: black
      - task: gen
      - task: dist
  
  install:
    desc: "install deps for the project"
    cmds:
      - cd web; pnpm install
      - poetry install
  
  black:
    desc: "format python with black"
    cmds:
      - black .
  
  db-init:
    desc: "create db via docker"
    dir: "{{.ROOT_DIR}}"
    cmds:
      - mkdir -p ./data/mongodb
      - docker run --name promptly-mongo -p 27017:27017 -p 8001:8001 -v ./data/mongodb:/data/db -d mongo
  
  db-restart:
    desc: "resest db via docker"
    dir: "{{.ROOT_DIR}}"
    cmds:
      - mkdir -p ./data/mongodb
      - docker stop promptly-mongo || docker container remove promptly-mongo || echo "done"
      - task: db-init
  
  db:
    desc: "start db via docker"
    cmds:
      - docker start promptly-mongo
  
  db-backup:
    desc: "backup db via docker"
    cmds:
      - |
        docker exec -it promptly-mongo \
        mongodump --db promptly --out /data/db/backup/
  
  gen:
    desc: "generate sdk via swagger"
    dir: "{{.ROOT_DIR}}"
    cmds:
      - rm -rf ./web/sdk
      - python bin/swagger.py
      - swagger-codegen generate -i ./data/swagger.json -l typescript-axios -o ./web/sdk
      - git add ./web/sdk
  
  dist:
    desc: "build for dist"
    dir: "{{.ROOT_DIR}}/web"
    cmds:
      - pnpm run build-only
  
  front:
    desc: start front for dev
    dir: "{{.ROOT_DIR}}/web"
    aliases:
      - "web"
      - "node"
    cmds:
      - pnpm run dev
  
  backend:
    desc: start backend for dev
    dir: "{{.ROOT_DIR}}"
    aliases:
      - "py"
    cmds:
      - uvicorn bin.main:app --reload
  
  run:
    desc: run server without reload
    dir: "{{.ROOT_DIR}}"
    cmds:
      - task: db
      - uvicorn bin.main:app
      