/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Message } from './message';
/**
 * 
 * @export
 * @interface RetrieveBody
 */
export interface RetrieveBody {
    /**
     * 
     * @type {string}
     * @memberof RetrieveBody
     */
    name: string;
    /**
     * 
     * @type {Array<Message>}
     * @memberof RetrieveBody
     */
    messages: Array<Message>;
}
