/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LLMOption } from './llmoption';
import { Message } from './message';
/**
 * 
 * @export
 * @interface ChatBody
 */
export interface ChatBody {
    /**
     * 
     * @type {Array<Message>}
     * @memberof ChatBody
     */
    messages: Array<Message>;
    /**
     * 
     * @type {LLMOption}
     * @memberof ChatBody
     */
    options: LLMOption;
}
