/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Argument } from './argument';
import { LLMOption } from './llmoption';
import { Message } from './message';
/**
 * 
 * @export
 * @interface CommitItem
 */
export interface CommitItem {
    /**
     * 
     * @type {Array<Argument>}
     * @memberof CommitItem
     */
    args?: Array<Argument>;
    /**
     * 
     * @type {LLMOption}
     * @memberof CommitItem
     */
    options?: LLMOption;
    /**
     * 
     * @type {Array<Message>}
     * @memberof CommitItem
     */
    messages: Array<Message>;
    /**
     * 
     * @type {string}
     * @memberof CommitItem
     */
    response?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitItem
     */
    md5?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommitItem
     */
    star?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommitItem
     */
    tag?: string;
}
