/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Argument } from './argument';
import { Message } from './message';
/**
 * Intended for use as a base class for externally-facing models.  Any models that inherit from this class will: * accept fields using snake_case or camelCase keys * use camelCase keys in the generated OpenAPI spec * have orm_mode on by default     * Because of this, FastAPI will automatically attempt to parse returned orm instances into the model
 * @export
 * @interface TestingRequestBody
 */
export interface TestingRequestBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof TestingRequestBody
     */
    sources: Array<string>;
    /**
     * 
     * @type {Array<Message>}
     * @memberof TestingRequestBody
     */
    messages: Array<Message>;
    /**
     * 
     * @type {string}
     * @memberof TestingRequestBody
     */
    argKey: string;
    /**
     * 
     * @type {Array<Argument>}
     * @memberof TestingRequestBody
     */
    args: Array<Argument>;
    /**
     * 
     * @type {string}
     * @memberof TestingRequestBody
     */
    model?: string;
}
