/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface StarBody
 */
export interface StarBody {
    /**
     * 
     * @type {string}
     * @memberof StarBody
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof StarBody
     */
    md5: string;
    /**
     * 
     * @type {boolean}
     * @memberof StarBody
     */
    value: boolean;
}
