/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * For event: each event maybe trigger by UI component with or without args. all args must come from the components like text / select and so on. we call the event `Update Event`.  then the event may come with an action, we call `Action Event`. this event means to do some actions (e.g. send a requests to server).  after all above, there must comes a `Response Event`. this event will send from backend server to front, with more events should be used to update UI.  of course, the event can work in duplex mode.
 * @export
 * @interface ActionEvent
 */
export interface ActionEvent {
    /**
     * 
     * @type {string}
     * @memberof ActionEvent
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ActionEvent
     */
    node: string;
}
