/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActionEvent } from './action-event';
import { UpdateEvent } from './update-event';
/**
 * 
 * @export
 * @interface EventRequest
 */
export interface EventRequest {
    /**
     * 
     * @type {string}
     * @memberof EventRequest
     */
    name: string;
    /**
     * 
     * @type {Array<UpdateEvent>}
     * @memberof EventRequest
     */
    updates: Array<UpdateEvent>;
    /**
     * 
     * @type {Array<ActionEvent>}
     * @memberof EventRequest
     */
    actions: Array<ActionEvent>;
}
