/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ArgRequest
 */
export interface ArgRequest {
    /**
     * 
     * @type {any}
     * @memberof ArgRequest
     */
    key: any;
    /**
     * 
     * @type {any}
     * @memberof ArgRequest
     */
    value: any;
}
