/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface Argument
 */
export interface Argument {
    /**
     * 
     * @type {any}
     * @memberof Argument
     */
    key: any;
    /**
     * 
     * @type {any}
     * @memberof Argument
     */
    value?: any;
    /**
     * 
     * @type {any}
     * @memberof Argument
     */
    candidates?: any;
}
