/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArgumentOutput } from './argument-output';
/**
 * 
 * @export
 * @interface ArgumentSetting
 */
export interface ArgumentSetting {
    /**
     * 
     * @type {string}
     * @memberof ArgumentSetting
     */
    name: string;
    /**
     * 
     * @type {Array<ArgumentOutput>}
     * @memberof ArgumentSetting
     */
    args: Array<ArgumentOutput>;
}
