/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArgumentInput } from './argument-input';
import { MessageInput } from './message-input';
/**
 * 
 * @export
 * @interface CommitItemInput
 */
export interface CommitItemInput {
    /**
     * 
     * @type {Array<ArgumentInput>}
     * @memberof CommitItemInput
     */
    args?: Array<ArgumentInput>;
    /**
     * 
     * @type {Array<MessageInput>}
     * @memberof CommitItemInput
     */
    messages: Array<MessageInput>;
    /**
     * 
     * @type {string}
     * @memberof CommitItemInput
     */
    response?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitItemInput
     */
    model?: string;
    /**
     * 
     * @type {string}
     * @memberof CommitItemInput
     */
    md5?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommitItemInput
     */
    star?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommitItemInput
     */
    tag?: string;
}
