/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArgumentOutput } from './argument-output';
import { MessageOutput } from './message-output';
/**
 * 
 * @export
 * @interface CommitItemOutput
 */
export interface CommitItemOutput {
    /**
     * 
     * @type {Array<ArgumentOutput>}
     * @memberof CommitItemOutput
     */
    args: Array<ArgumentOutput>;
    /**
     * 
     * @type {Array<MessageOutput>}
     * @memberof CommitItemOutput
     */
    messages: Array<MessageOutput>;
    /**
     * 
     * @type {string}
     * @memberof CommitItemOutput
     */
    response: string;
    /**
     * 
     * @type {string}
     * @memberof CommitItemOutput
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof CommitItemOutput
     */
    md5: string;
    /**
     * 
     * @type {boolean}
     * @memberof CommitItemOutput
     */
    star: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommitItemOutput
     */
    tag: string;
}
