/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface CommitItem
 */
export interface CommitItem {
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    args?: any;
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    messages: any;
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    response?: any;
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    model?: any;
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    md5?: any;
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    star?: any;
    /**
     * 
     * @type {any}
     * @memberof CommitItem
     */
    tag?: any;
}
