/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface MessageInput
 */
export interface MessageInput {
    /**
     * 
     * @type {string}
     * @memberof MessageInput
     */
    role: string;
    /**
     * 
     * @type {string}
     * @memberof MessageInput
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof MessageInput
     */
    enable?: boolean;
}
