/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ModelCase
 */
export interface ModelCase {
    /**
     * 
     * @type {number}
     * @memberof ModelCase
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ModelCase
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ModelCase
     */
    data: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ModelCase
     */
    description: string;
}
