/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommitItemInput } from './commit-item-input';
/**
 * 
 * @export
 * @interface NewCommitBody
 */
export interface NewCommitBody {
    /**
     * 
     * @type {CommitItemInput}
     * @memberof NewCommitBody
     */
    commit: CommitItemInput;
    /**
     * 
     * @type {string}
     * @memberof NewCommitBody
     */
    name: string;
}
