/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArgumentOutput } from './argument-output';
import { MessageOutput } from './message-output';
/**
 * 
 * @export
 * @interface Prompt
 */
export interface Prompt {
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    model: string;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    defaultModel: string;
    /**
     * 
     * @type {Array<MessageOutput>}
     * @memberof Prompt
     */
    messages: Array<MessageOutput>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Prompt
     */
    history: Array<string>;
    /**
     * 
     * @type {Array<ArgumentOutput>}
     * @memberof Prompt
     */
    args: Array<ArgumentOutput>;
    /**
     * 
     * @type {string}
     * @memberof Prompt
     */
    group: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Prompt
     */
    plugins: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Prompt
     */
    docs: Array<string>;
}
