/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TestCase
 */
export interface TestCase {
    /**
     * 
     * @type {number}
     * @memberof TestCase
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof TestCase
     */
    data?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TestCase
     */
    description?: string;
}
