/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface TestingRequestBody
 */
export interface TestingRequestBody {
    /**
     * 
     * @type {any}
     * @memberof TestingRequestBody
     */
    sources: any;
    /**
     * 
     * @type {any}
     * @memberof TestingRequestBody
     */
    messages: any;
    /**
     * 
     * @type {any}
     * @memberof TestingRequestBody
     */
    key: any;
    /**
     * 
     * @type {any}
     * @memberof TestingRequestBody
     */
    args: any;
}
