/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ArgumentInput } from './argument-input';
import { MessageInput } from './message-input';
/**
 * 
 * @export
 * @interface TestingRequestBody
 */
export interface TestingRequestBody {
    /**
     * 
     * @type {Array<string>}
     * @memberof TestingRequestBody
     */
    sources: Array<string>;
    /**
     * 
     * @type {Array<MessageInput>}
     * @memberof TestingRequestBody
     */
    messages: Array<MessageInput>;
    /**
     * 
     * @type {string}
     * @memberof TestingRequestBody
     */
    argKey: string;
    /**
     * 
     * @type {Array<ArgumentInput>}
     * @memberof TestingRequestBody
     */
    args: Array<ArgumentInput>;
    /**
     * 
     * @type {string}
     * @memberof TestingRequestBody
     */
    model?: string;
}
