/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface UpdatePromptBody
 */
export interface UpdatePromptBody {
    /**
     * 
     * @type {any}
     * @memberof UpdatePromptBody
     */
    messages?: any;
    /**
     * 
     * @type {any}
     * @memberof UpdatePromptBody
     */
    model?: any;
    /**
     * 
     * @type {any}
     * @memberof UpdatePromptBody
     */
    args?: any;
    /**
     * 
     * @type {any}
     * @memberof UpdatePromptBody
     */
    defaultModel?: any;
}
